export * from "./MainTemplate/MainTemplate";
export * from "./MoviesList/MoviesList";
export * from "./MovieCard/MovieCard";
export * from "./Nav/Nav";
export * from "./Search/Search";
export * from "./Header/Header";
export * from "./UserProfile/UserProfile";
export * from "./SideBar/SideBar";
export * from "./CustomNavLink/CustomNavLink";
